stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
      - src/data_collection.py
    outs:
      - data/raw

  preprocess:
    cmd: python src/data_preprocessing.py
    deps:
      - data/raw/train.csv
      - data/raw/test.csv
      - src/data_preprocessing.py
    outs:
      - data/processed/train_processed.csv
      - data/processed/test_processed.csv
